### ISSUE TITLE
[Docs] Git Commit Convension / Issues Template / Pull requests Template

### ISSUE THREAD

**Issue by jwon42** [humansof42seoul/Humansof42-v2#2]
- [x] Git Commit Message Conventions 8b4297f
  - https://github.com/humansof42seoul/Humansof42-v2/blob/master/docs/Commit_Conventions.md
- [x] Issues Template 세팅 dee3462
  - 이슈 생성 시 Bug Report, Feature Request 에 해당한다면 템플릿을 이용해주세요. 강제사항은 아니고 좀 더 편하게 하시라고..
  - 이슈 생성 시 Labels 중 Priority, Status, Type을 한가지씩 선택해주세요. 
- [x] Pull requests Template 세팅 #3 
  - https://github.com/humansof42seoul/Humansof42-v2/blob/master/.github/PULL_REQUEST_TEMPLATE.md

**기본적인 컨벤션이 담긴 이슈이기 때문에 Close 하지 않겠습니다.**

**Comment by jwon42** [comment]
@jongfeel 
협업 시 명확한 커뮤니케이션을 위해 issue template, pr template이 필요할 것 같습니다.
그 중 issue template 카테고리를 제안해주실 수 있을까요? 일단 bug report, feature request를 생각하고 있습니다.

**Comment by jongfeel** [comment]
template이 있으면 좋을 수 있지만... 해 보면서 만들어 보면 좋을 수 있습니다.
저는 자유롭게 작성하는걸 좋아해서 template을 선호하지는 않아서요.
또 template이 주어지면 거기에 맞춰서만 쓰려고 하고 정작 본인이 할 얘기는 못쓰는 경우도 있어서 그렇습니다.

feature는 task 정도로 분리해서 해 보면 될 거고 
bug는 재현 절차, 로그 스크린샷 정도를 추가해 두면 좋긴 합니다.

**Comment by jwon42** [comment]
> template이 있으면 좋을 수 있지만... 해 보면서 만들어 보면 좋을 수 있습니다. 저는 자유롭게 작성하는걸 좋아해서 template을 선호하지는 않아서요. 또 template이 주어지면 거기에 맞춰서만 쓰려고 하고 정작 본인이 할 얘기는 못쓰는 경우도 있어서 그렇습니다.
> 
> feature는 task 정도로 분리해서 해 보면 될 거고 bug는 재현 절차, 로그 스크린샷 정도를 추가해 두면 좋긴 합니다.
